### ISSUE TITLE
내 그룹 홈 화면 api들 구현

### ISSUE THREAD

**Issue by LeeKing2017** [WeMingle/WeMingle_CoreServer#123]
# **Issue**

## Issue Type

- [x] New feature
- [ ] Refactor
- [ ] Bug fix
- [ ] Chore
- [ ] Style
- [ ] Test

--- 

#  📝Description

내 그룹 화면에 필요한 api 구현

---

## Todo
- [x] 내가 속한 팀이 있는 지와 학교 인증했는 지 확인 api
- [x] 위밍글이 추천하는 팀 조회 api
- [x] 사용자가 속한 학교의 팀 조회 api
- [x] 내가 속한 팀들의 글 조회 api
- [x] 사용자를 위한 추천 팀 조회 api
- [x] 검색명으로 팀 조회 api
- [x] 검색명으로 사용자 조회 api
- [x] 내가 속한 팀들의 게시글 조회 api
