### ISSUE TITLE
팀에서 관리자 권한 부가 기능에 따른 수정

### ISSUE THREAD

**Issue by LeeKing2017** [WeMingle/WeMingle_CoreServer#124]
# **Issue**

## Issue Type

- [ ] New feature
- [x] Refactor
- [ ] Bug fix
- [ ] Chore
- [ ] Style
- [ ] Test

--- 

#  📝Description

팀에서 관리자 권한을 멤버들에게 주는 기능에 따른 서비스 로직들 수정 필요

---

## Todo
- [x] 매칭글 작성 전 팀 프로필 조회 api 수정
- [x] 매칭 리스트에서 매칭 피드 조회 api 수정
- [x] 매칭 리스트에서 히스토리 조회 api 수정
- [x] 팀의 승인 대기 리스트 api 수정
