### ISSUE TITLE
팀 상세보기 api 구현

### ISSUE THREAD

**Issue by LeeKing2017** [WeMingle/WeMingle_CoreServer#128]
# **Issue**

## Issue Type

- [x] New feature
- [ ] Refactor
- [ ] Bug fix
- [ ] Chore
- [ ] Style
- [ ] Test

--- 

#  📝Description

팀 상세보기 화면에서 사용할 api 구현

---

## Todo
- [x] 팀 정보 조회 api  
- [x] 팀 피드의 글들 조회 api
- [x] 팀의 조건에 부합하는 지 확인하는 api
