### ISSUE TITLE
이슈 테스트

### ISSUE THREAD

**Issue by LeeKing2017** [WeMingle/WeMingle_CoreServer#14]
# **Issue**

## Issue Type

- [ ] Chore
- [ ] Style
- [ ] Test

--- 

#  📝Description

어느 이슈인지 간단한 설명을 적어주세요.

---

## Todo
- [ ] Todo 
- [ ] Todo

---

## Check list
- [ ] 개발영역, 개발자 이름, issue type 순으로 라벨을 설정하셨나요? Ex. 백엔드, 이호왕, Feature
- [ ] 프로젝트에 issue 등록하셨나요?
- [ ] commit에 issue 연동을 하셨나요?
