### ISSUE TITLE
그룹 신청 api 구현

### ISSUE THREAD

**Issue by LeeKing2017** [WeMingle/WeMingle_CoreServer#169]
# **Issue**

## Issue Type

- [x] New feature
- [ ] Refactor
- [ ] Bug fix
- [ ] Chore
- [ ] Style
- [ ] Test

--- 

#  📝Description

그룹 신청 기능 추가

---

## Todo
- [x] 프로필 사진, 닉네임, 내 정보, 자유 질문 조회 api 구현
- [x] 팀 내에서 닉네임 중복 체크 api 구현
- [x] 그룹 신청하는 api 구현
- [x] 그룹 신청 페이지에서 사진 저장 링크 발급 api 구현
