### ISSUE TITLE
팀 설정 변경 api 구현

### ISSUE THREAD

**Issue by LeeKing2017** [WeMingle/WeMingle_CoreServer#199]
# **Issue**

## Issue Type

- [x] New feature
- [ ] Refactor
- [ ] Bug fix
- [ ] Chore
- [ ] Style
- [ ] Test

--- 

#  📝Description

팀 설정 변경 api 구현

---

## Todo
- [x] 팀 entity에  배경화면 이름 컬럼 추가  
- [x] 팀의 설정 변경 api 구현
- [x] 팀 설정 조회 api 구현
- [x] 팀 배경사진 업로드 링크 발급 api 구현
