### ISSUE TITLE
jwt의 Role에 unVerifiedUser 추가

### ISSUE THREAD

**Issue by LeeKing2017** [WeMingle/WeMingle_CoreServer#23]
# **Issue**

## Issue Type

- [x] Refactor

--- 

#  📝Description

학교 인증 전에 사용자의 role은 UnVerifiedUser로 사용할 수 있는 애플리케이션 범위가 제한된다.

---

## Todo
- [x] jwt 구현 로직에서 role에 UnVerifiedUser 추가
- [x] 학교 미인증 사용자의 토큰 발급 메소드 구현
- [x] 학교 인증 시 Role이 unVerfiedUser -> User로 변경 메소드 구현
